openapi: 3.0.1
info:
  title: FSL
  description: Fascicolo Sociale e Lavorativo del Cittadino
  contact:
    name: DG Innovazione
    email: dginnovazionediv3@lavoro.gov.it
  version: 1.0.0
  x-summary: Fascicolo Sociale e Lavorativo del Cittadino
  x-semantic-score: 0.33
  x-semantic-score-timestamp: 1774016775575
servers:
  - url: https://apimlpstest.lavoro.gov.it/rest
    description: FSL Test Environment
  - url: https://apimlps.lavoro.gov.it/rest
    description: FSL Production Environment
paths:
  /fsl/v1/offerteFormative/idOfferta/{codiceCorso}:
    get:
      tags:
        - Siisl
      summary: Recupero identificativo Offerta formativa
      description: Dato un codice corso formativo, il servizio restituisce il relativo id offerta
      operationId: RecuperoIdOffertaFormativa
      parameters:
        - name: codiceCorso
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSL.Api.Domain.Models.OfferteFormative.RecuperoIdSiislOffertaFormativa'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '500':
          description: Internal Server Error
  /status:
    get:
      tags:
        - Health Check API
      description: Returns the health status of this service
      operationId: HealthCheckStatus
      responses:
        '200':
          description: API service is healthy
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/FSL.Common.Support.Models.Api.HealthCheckSuccess'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '500':
          description: Internal Server Error
        '503':
          description: API service is not healthy
components:
  schemas:
    FSL.Api.Domain.Models.OfferteFormative.RecuperoIdSiislOffertaFormativa:
      type: object
      properties:
        idOfferta:
          type: string
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/labour-social-policies/onto/labour/OffertaFormativa
      x-jsonld-context:
        "@vocab": https://w3id.org/italia/labour-social-policies/onto/labour/
        idOfferta: idOffertaFormativa
      example:
        idOfferta: '02301900268-000022'

    FSL.Common.Support.Models.Api.HealthCheckSuccess:
      type: object
      properties:
        status:
          type: string
        totalDuration:
          type: string
        entries: {}
        title:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
      additionalProperties: false

    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
tags:
  - name: Siisl
    description: Siisl
  - name: Health Check API
    description: Health Check API
