openapi: 3.0.1
info:
  title: FSL
  description: Fascicolo Sociale e Lavorativo del Cittadino
  contact:
    name: DG Innovazione
    email: dginnovazionediv3@lavoro.gov.it
  version: 1.0.0
  x-summary: Fascicolo Sociale e Lavorativo del Cittadino
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  x-semantic-score: 0.33
  x-semantic-score-timestamp: 1774016337795
servers:
  - url: https://apimlpstest.lavoro.gov.it/rest
    description: FSL Test Environment
  - url: https://apimlps.lavoro.gov.it/rest
    description: FSL Production Environment
paths:
  /fsl/v1/cittadino/offerte/interessi:
    post:
      tags:
        - Siisl
      summary: Consultazione manifestazione di Interesse a Offerte di lavoro
      description: Dato il codice fiscale di un cittadino (più gli eventuali dati dell'entità chiamante), il servizio restituisce le offerte di lavoro per le quali il CF ha manifestato interesse
      operationId: ConsultazioneInteressiOfferteLavoro
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSL.Api.Domain.Models.Siisl.InputConsultazione'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSL.Api.Domain.Models.Siisl.ConsultazioneInteressiOfferteLavoro.InteressiOfferteLavoro_Output'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '500':
          description: Internal Server Error
  /status:
    get:
      tags:
        - Health Check API
      description: Returns the health status of this service
      operationId: HealthCheckStatus
      responses:
        '200':
          description: API service is healthy
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/FSL.Common.Support.Models.Api.HealthCheckSuccess'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '500':
          description: Internal Server Error
        '503':
          description: API service is not healthy

components:
  schemas:
    FSL.Api.Domain.Models.Siisl.ConsultazioneInteressiOfferteLavoro.InteressiOfferteLavoro_Output:
      type: object
      properties:
        interessiOfferteLavoro:
          type: array
          items:
            $ref: '#/components/schemas/FSL.Api.Domain.Models.Siisl.ConsultazioneInteressiOfferteLavoro.OffertaInteresse'
      additionalProperties: false
    FSL.Api.Domain.Models.Siisl.ConsultazioneInteressiOfferteLavoro.OffertaInteresse:
      type: object
      properties:
        dataManifestazione:
          type: string
          format: date-time
        offertaDiLavoro:
          $ref: '#/components/schemas/FSL.Api.Domain.Models.Siisl.ConsultazioneInteressiOfferteLavoro.OffertaLavoro'
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/labour-social-policies/onto/labour/ManifestazioneInteresseOffertaDiLavoro
      x-jsonld-context:
        "@vocab": https://w3id.org/italia/labour-social-policies/onto/labour/
        dataManifestazione: dataManifestazioneInteresseOffertaDiLavoro
        offertaDiLavoro:
          '@id': haOffertaDiLavoroDiInteresse
      example:
        dataManifestazione: '2025-01-14T00:00:00Z'
    FSL.Api.Domain.Models.Siisl.ConsultazioneInteressiOfferteLavoro.OffertaLavoro:
      type: object
      properties:
        codice:
          type: string
        titolo:
          type: string
          nullable: true
        descrizione:
          type: string
          nullable: true
        stato:
          type: string
        origine:
          type: string
        dataPubblicazione:
          type: string
          format: date-time
        dataScadenza:
          type: string
          format: date-time
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/labour-social-policies/onto/labour/OffertaDiLavoro
      x-jsonld-context:
        "@vocab": https://w3id.org/italia/labour-social-policies/onto/labour/
        codice: codiceOffertaDiLavoro
        titolo: titoloOffertaDiLavoro
        descrizione: descrizioneOffertaDiLavoro
        stato: statusOffertaDiLavoro
        origine:
          '@id': haCanaleDiOrigineOffertaDiLavoro
          '@type': '@id'
          '@context':
              "@base": 'https://w3id.org/italia/labour-social-policies/controlled-vocabulary/data/origine_offerta_lavoro/'
              id: '@id'
              label: http://www.w3.org/2000/01/rdf-schema#label
        dataPubblicazione: dataPubblicazioneOffertaDiLavoro
        dataScadenza: dataScadenzaOffertaDiLavoro
      example:
        codice: '0000F068351000015'
        titolo: 'Titolo Test'
        descrizione: 'Descrzione offerta lavoro'
        stato: 'Pubblicata'
        origine: '1'
        dataPubblicazione: '2025-01-14T00:00:00Z'
        dataScadenza: '2025-01-14T00:00:00Z'

    FSL.Api.Domain.Models.Siisl.InputConsultazione:
      required:
        - codiceFiscaleCittadino
      type: object
      properties:
        codiceATS:
          type: string
          nullable: true
        comuni:
          type: array
          items:
            type: string
          nullable: true
        cfOperatore:
          type: string
          nullable: true
        codiceFiscaleCittadino:
          minLength: 1
          type: string
      additionalProperties: false


    FSL.Common.Support.Models.Api.HealthCheckSuccess:
      type: object
      properties:
        status:
          type: string
        totalDuration:
          type: string
        entries: {}
        title:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
      additionalProperties: false
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
tags:
  - name: Siisl
    description: Siisl
  - name: Health Check API
    description: Health Check API
