openapi: 3.0.1
info:
  title: FSL
  description: Fascicolo Sociale e Lavorativo del Cittadino
  contact:
    name: DG Innovazione
    email: dginnovazionediv3@lavoro.gov.it
  version: 1.0.0
  x-summary: Fascicolo Sociale e Lavorativo del Cittadino
  x-semantic-score: 0.17
  x-semantic-score-timestamp: 1775576822452
servers:
  - url: https://apimlpstest.lavoro.gov.it/rest
    description: FSL Test Environment
  - url: https://apimlps.lavoro.gov.it/rest
    description: FSL Production Environment
paths:
  /fsl/areasociale/v1/salva-sostegni:
    post:
      tags:
        - Gepi
      summary: Registrazione Sostegni
      description: Il servizio permette la registrazione dei sostegni assegnati ai cittadini beneficiari, compresi i tirocini sociali (in input) e restituisce in output l’esito dell’operazione
      operationId: RegistrazioneSostegni
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.RegistrazioneSostegni.RegistrazioneSostegni_Input'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.RegistrazioneSostegni.RegistrazioneSostegni_Output'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '500':
          description: Internal Server Error
  /status:
    get:
      tags:
        - Health Check API
      description: Returns the health status of this service
      operationId: HealthCheckStatus
      responses:
        '200':
          description: API service is healthy
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/FSL.Common.Support.Models.Api.HealthCheckSuccess'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
        '500':
          description: Internal Server Error
        '503':
          description: API service is not healthy
components:
  schemas:
    FSL.Api.Domain.Models.Gepi.Esito:
      required:
        - codiceEsito
        - descrizioneEsito
      type: object
      properties:
        codiceEsito:
          minLength: 1
          type: string
        descrizioneEsito:
          minLength: 1
          type: string
      additionalProperties: false
    FSL.Api.Domain.Models.Gepi.RegistrazioneSostegni.RegistrazioneSostegni_Input:
      required:
        - cFOperatore
        - identificativoCaso
        - modalitaAccesso
        - sostegni
      type: object
      properties:
        codiceATS:
          type: string
          nullable: true
        comuni:
          type: array
          items:
            type: string
          nullable: true
        modalitaAccesso:
          type: integer
          format: int32
        cFOperatore:
          minLength: 1
          type: string
        identificativoCaso:
          minLength: 1
          type: string
        sostegni:
          type: array
          items:
            $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.RegistrazioneSostegni.Sostegno'
      additionalProperties: false
    FSL.Api.Domain.Models.Gepi.RegistrazioneSostegni.RegistrazioneSostegni_Output:
      required:
        - esito
      type: object
      properties:
        esito:
          $ref: '#/components/schemas/FSL.Api.Domain.Models.Gepi.Esito'
      additionalProperties: false
    FSL.Api.Domain.Models.Gepi.RegistrazioneSostegni.Sostegno:
      required:
        - codiceFiscale
        - idTipologia
        - tipologia
      type: object
      properties:
        tipologia:
          minLength: 1
          type: string
        idTipologia:
          minLength: 1
          type: string
        codiceFiscale:
          minLength: 1
          type: string
        dataAvvio:
          type: string
          nullable: true
        dataAvvioPrevista:
          type: string
          nullable: true
        dataFine:
          type: string
          nullable: true
        dataAssegnazione:
          type: string
          nullable: true
      additionalProperties: false
      x-jsonld-type: https://w3id.org/italia/labour-social-policies/onto/social/SostegnoPaIS
      x-jsonld-context:
        "@vocab": https://w3id.org/italia/labour-social-policies/onto/social/
        tipologia: descrizioneTipologiaSostegnoPaIS
        idTipologia: idTipologiaSostegnoPaIS
        codiceFiscale: https://w3id.org/italia/onto/CPV/taxCode
        dataAvvio: dataAvvioSostegno
        dataAvvioPrevista: dataPrevistaAvvioSostegno
        dataFine: dataFineSostegno
        dataAssegnazione: dataAssegnazioneSostegno
      example:
        tipologia: 'Formazione per il conseguimento di Qualifiche professionali'
        idTipologia: 'bcc888fd-00c7-43ef-8edb-e2bc9b147d17'
        codiceFiscale: 'AAAAAA00A00A000A'
        dataAvvio: '2025-02-01'
        dataAvvioPrevista: '2025-02-15'
        dataFine: '2025-12-31'
        dataAssegnazione: '2025-02-07'

    FSL.Common.Support.Models.Api.HealthCheckSuccess:
      type: object
      properties:
        status:
          type: string
        totalDuration:
          type: string
        entries: {}
        title:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
      additionalProperties: false
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: {}
tags:
  - name: Gepi
    description: Gepi
  - name: Health Check API
    description: Health Check API
